name: Deploy to Maven Central

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache for maven dependencies
        id: cache-maven-restore
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-repo-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Setup settings.xml
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [
               {
                  "id":"central",
                  "username":"${{ secrets.SONATYPE_USER }}",
                  "password":"${{ secrets.SONATYPE_PASSWORD }}"
               }
            ]
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build with Maven
        run: mvn -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} clean deploy

      - name: Update cache for maven dependencies
        id: cache-maven-save
        if: steps.cache-maven-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-repo-${{ hashFiles('**/pom.xml') }}