name: Deploy to Maven Central

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    steps:
      - uses: actions/checkout@v2
      # Step that does that actual cache save and restore
      - name: Setup settings.xml
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [
               {
                  "id":"sonatype-nexus-snapshots",
                  "username":"${{ secrets.SONATYPE_USER }}",
                  "password":"${{ secrets.SONATYPE_PASSWORD }}"
               },
               {
                  "id":"sonatype-nexus-staging",
                  "username":"${{ secrets.SONATYPE_USER }}",
                  "password":"${{ secrets.SONATYPE_PASSWORD }}"
               }
            ]
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build with Maven
        run: mvn -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} clean deploy